"""Dati di prova per testare il grafo senza MySQL/Ollama collegati.

687 frasi di esempio gia' taggate a mano: i tag si ripetono e si
intrecciano tra le frasi, cosi' la nebulosa risulta fitta e collegata.
"""

from src import db_local
from src.logging_utils import get_logger

log = get_logger(__name__)

# (testo, tag...)
_RAW = [
    # --- le 6 frasi originali ---
    ("Ti voglio bene", "amore", "connessione"),
    ("La forza sta nelle relazioni", "connessione", "forza"),
    ("Impara giocando", "gioco", "apprendimento"),
    ("Il gioco è la base della creatività", "gioco", "creativita"),
    ("Capire se stessi richiede consapevolezza", "apprendimento", "consapevolezza"),
    ("L'umorismo aiuta ad affrontare le sfide", "umorismo", "sfida"),
    # --- amore ---
    ("Ti aspetto anche se so che non tornerai", "amore", "memoria"),
    ("Il tuo nome è la prima cosa che dimentico e l'ultima che perdo", "amore", "memoria"),
    ("Abbracciami come se il mondo finisse tra un minuto", "amore", "paura"),
    ("Ho imparato ad amare guardandoti dormire", "amore", "notte"),
    ("L'amore è restare quando andarsene sarebbe più facile", "amore", "coraggio"),
    ("Non so cosa siamo, ma mi piace non saperlo", "amore", "identita"),
    ("Ogni volta che ridi il tempo rallenta", "amore", "tempo"),
    ("Ti ho perdonato prima ancora che tu chiedessi scusa", "perdono", "amore"),
    ("Il mio posto preferito è accanto a te", "amore", "casa"),
    ("Ci siamo amati male, ma ci siamo amati", "amore", "perdono"),
    # --- amicizia ---
    ("Un vero amico sa quando non parlare", "amicizia", "silenzio"),
    ("Le amicizie che restano sono quelle che non fanno rumore", "amicizia", "silenzio"),
    ("Ho un amico che mi conosce meglio di me", "amicizia", "consapevolezza"),
    ("Ridere con qualcuno fino alle lacrime è una forma di preghiera", "amicizia", "umorismo"),
    ("Ci siamo persi senza litigare, ed è la cosa più triste", "amicizia", "nostalgia"),
    ("Chiamami alle tre di notte, risponderò", "amicizia", "notte"),
    ("Da bambini bastava un pallone per essere fratelli", "amicizia", "gioco"),
    ("Gli amici sono la famiglia che scegliamo", "amicizia", "famiglia"),
    ("Ho ancora il biglietto che mi hai scritto in terza media", "amicizia", "memoria"),
    ("Non serve essere d'accordo per volersi bene", "amicizia", "connessione"),
    # --- famiglia e casa ---
    ("Mia nonna cucinava per dieci anche quando eravamo in tre", "famiglia", "cibo"),
    ("La casa è dove qualcuno ti lascia la luce accesa", "casa", "amore"),
    ("Papà non diceva mai ti voglio bene, ma aggiustava tutto", "famiglia", "amore"),
    ("Il profumo del sugo la domenica è la mia infanzia", "cibo", "memoria"),
    ("Mia madre canticchiava sempre, anche nei giorni brutti", "famiglia", "musica"),
    ("Torno a casa e ridiventa tutto piccolo", "casa", "nostalgia"),
    ("Siamo fatti dei silenzi dei nostri genitori", "famiglia", "silenzio"),
    ("Le chiavi di casa dei nonni le tengo ancora in tasca", "casa", "lutto"),
    ("Mio fratello è il mio primo e ultimo complice", "famiglia", "gioco"),
    ("A tavola si litiga e si fa pace con lo stesso piatto", "famiglia", "cibo"),
    ("Ho cambiato dieci case, ma una sola mi chiama ancora", "casa", "memoria"),
    ("I figli sono una promessa che facciamo al futuro", "famiglia", "speranza"),
    # --- Napoli e mare ---
    ("Napoli ti abbraccia e ti scippa nello stesso momento", "napoli", "umorismo"),
    ("Il mare a Posillipo alle sei del mattino non ha bisogno di parole", "mare", "napoli"),
    ("Chi nasce qui porta il Vesuvio dentro", "napoli", "identita"),
    ("Il caffè sospeso è la nostra poesia", "napoli", "gratitudine"),
    ("Ho lasciato Napoli, ma Napoli non ha lasciato me", "napoli", "nostalgia"),
    ("Il mare non ha mai fretta e non sbaglia mai", "mare", "tempo"),
    ("Sul lungomare tutti i problemi sembrano più piccoli", "mare", "speranza"),
    ("Nel vicolo si sente cantare anche quando nessuno canta", "napoli", "musica"),
    ("L'acqua salata guarisce quello che le parole non arrivano a toccare", "mare", "silenzio"),
    ("Ogni onda è un pensiero che torna", "mare", "memoria"),
    ("Solo a Napoli il caos ha un suo ordine", "napoli", "consapevolezza"),
    ("Un tramonto sul golfo vale una vita di stipendi", "napoli", "felicita"),
    # --- memoria, nostalgia, tempo ---
    ("Il tempo non guarisce, insegna a camminare zoppicando", "tempo", "forza"),
    ("Ho paura di dimenticare la sua voce", "memoria", "lutto"),
    ("Certi odori sono macchine del tempo", "memoria", "nostalgia"),
    ("Le foto sono bugie dolci", "memoria", "identita"),
    ("Ieri era meglio solo perché non sapevo come andava a finire", "nostalgia", "tempo"),
    ("Il passato non passa, cambia stanza", "memoria", "tempo"),
    ("Conservo i biglietti del cinema come reliquie", "memoria", "amore"),
    ("Non torniamo mai negli stessi posti, torniamo negli stessi noi", "nostalgia", "identita"),
    ("Il tempo è l'unico ladro che ci lascia più di quel che prende", "tempo", "gratitudine"),
    ("Ho smesso di contare gli anni e ho iniziato a contare le risate", "tempo", "felicita"),
    ("Ogni orologio fermo ha ragione due volte al giorno", "tempo", "umorismo"),
    ("La nostalgia è amore che non sa dove andare", "nostalgia", "amore"),
    # --- paura e coraggio ---
    ("Il coraggio è avere paura e aprire lo stesso la porta", "coraggio", "paura"),
    ("Ho paura del buio solo quando sono solo", "paura", "solitudine"),
    ("Non sono coraggioso, sono solo troppo stanco di scappare", "coraggio", "forza"),
    ("La paura è una bussola che indica dove devo andare", "paura", "consapevolezza"),
    ("Ho detto la verità e il cielo non è crollato", "coraggio", "liberta"),
    ("Le mie paure hanno il volto di persone che amo", "paura", "amore"),
    ("Ogni mattina scegliere di alzarsi è un atto eroico", "coraggio", "forza"),
    ("Il salto più difficile è quello dentro di sé", "coraggio", "consapevolezza"),
    ("Ho fatto il primo passo tremando e ora non mi fermo", "coraggio", "cambiamento"),
    ("Ho paura di non essere abbastanza", "paura", "identita"),
    # --- speranza e felicità ---
    ("Domani è una porta che non ho ancora aperto", "speranza", "tempo"),
    ("La speranza è testardaggine con un bel vestito", "speranza", "umorismo"),
    ("Anche la notte più lunga finisce all'alba", "speranza", "notte"),
    ("Sono felice e non so perché, e va benissimo così", "felicita", "consapevolezza"),
    ("La felicità è un caffè caldo e nessuna fretta", "felicita", "cibo"),
    ("Ho imparato che essere felici è un lavoro quotidiano", "felicita", "lavoro"),
    ("Spero che qualcuno stasera pensi a me", "speranza", "solitudine"),
    ("Semino cose piccole e aspetto miracoli grandi", "speranza", "natura"),
    ("La felicità arriva quando smetto di cercarla", "felicita", "liberta"),
    ("C'è luce anche nelle crepe", "speranza", "forza"),
    ("Sorridere a uno sconosciuto ha cambiato la mia giornata", "felicita", "connessione"),
    ("Il meglio deve ancora arrivare, lo dico ogni giorno", "speranza", "gratitudine"),
    # --- solitudine e silenzio ---
    ("Stare da soli è diverso dal sentirsi soli", "solitudine", "consapevolezza"),
    ("Nel silenzio di casa sento tutto quello che non dico", "silenzio", "solitudine"),
    ("Parlo con le piante perché almeno non mi interrompono", "solitudine", "umorismo"),
    ("Il silenzio dopo un litigio pesa più delle parole", "silenzio", "rabbia"),
    ("Sono circondato di gente e mi manca qualcuno", "solitudine", "connessione"),
    ("Ho imparato a farmi compagnia", "solitudine", "forza"),
    ("La città di notte è un'enorme stanza vuota", "notte", "solitudine"),
    ("Nessuno mi ha chiesto come sto davvero", "solitudine", "connessione"),
    ("Il silenzio è la lingua che tutti capiscono", "silenzio", "connessione"),
    ("Ogni tanto spengo tutto e ascolto il respiro", "silenzio", "consapevolezza"),
    # --- libertà e sogni ---
    ("Voglio svegliarmi senza sveglia e senza doveri", "liberta", "tempo"),
    ("Ho sognato di volare e non volevo atterrare", "sogno", "liberta"),
    ("I sogni sono lettere che ci scriviamo di notte", "sogno", "notte"),
    ("La libertà non è fare ciò che voglio, è non temere di volere", "liberta", "coraggio"),
    ("Un giorno partirò con uno zaino e nessuna meta", "viaggio", "liberta"),
    ("Ho un sogno che non racconto per non spaventarlo", "sogno", "paura"),
    ("Sognare è gratis, e io ne approfitto", "sogno", "umorismo"),
    ("Da bambino disegnavo mondi e ci abitavo", "sogno", "creativita"),
    ("Ho lasciato il lavoro sicuro per il sogno incerto", "sogno", "coraggio"),
    ("Il sogno più bello è quello che ti fa alzare presto", "sogno", "lavoro"),
    ("Volare è solo cadere con un po' di fede", "liberta", "speranza"),
    ("Sogno un mondo dove nessuno ha fretta", "sogno", "tempo"),
    # --- gioco, creatività, apprendimento, umorismo ---
    ("Non smettere di giocare: si invecchia quando si smette", "gioco", "tempo"),
    ("Ho imparato più dai fallimenti che dai libri", "apprendimento", "sfida"),
    ("La creatività è un muscolo, e io lo alleno sbagliando", "creativita", "apprendimento"),
    ("Ridere di sé è il primo passo per perdonarsi", "umorismo", "perdono"),
    ("Il modo migliore per capire qualcosa è provare a spiegarlo a un bambino", "apprendimento", "famiglia"),
    ("Mi piace disegnare male: nessuno mi giudica", "creativita", "liberta"),
    ("Ogni errore è un professore che non manda il conto", "apprendimento", "umorismo"),
    ("Costruire castelli di sabbia insegna a lasciar andare", "gioco", "mare"),
    ("Ho cantato sotto la doccia e ho scritto la mia canzone migliore", "musica", "creativita"),
    ("L'ironia è la corazza dei sensibili", "umorismo", "forza"),
    ("Le regole del gioco cambiano quando smetti di temere di perdere", "gioco", "coraggio"),
    ("Imparo una parola nuova ogni giorno e mi sento più grande", "apprendimento", "felicita"),
    ("Chi ride per ultimo aveva capito la battuta dopo", "umorismo", "tempo"),
    ("Scrivere è ascoltare quello che ho già dentro", "creativita", "consapevolezza"),
    ("La curiosità è la mia religione", "apprendimento", "identita"),
    ("Faccio il buffone perché la serietà mi fa paura", "umorismo", "paura"),
    ("Il gioco è la cosa più seria che ci sia", "gioco", "consapevolezza"),
    ("Ho sbagliato strada e ho trovato il posto più bello", "viaggio", "apprendimento"),
    # --- musica ---
    ("Una canzone può riportarmi dove vuole", "musica", "memoria"),
    ("Ballo in cucina quando nessuno guarda", "musica", "felicita"),
    ("La musica è la lingua con cui Dio ci perdona", "musica", "perdono"),
    ("Ascolto lo stesso disco da vent'anni e ogni volta è nuovo", "musica", "tempo"),
    ("Quando suono smetto di pensare e comincio a esistere", "musica", "consapevolezza"),
    ("Le note sono ponti tra chi non sa parlarsi", "musica", "connessione"),
    ("Ho pianto a un concerto senza sapere perché", "musica", "gratitudine"),
    # --- natura e viaggio ---
    ("Gli alberi non hanno fretta e arrivano ovunque", "natura", "tempo"),
    ("Il bosco dopo la pioggia è la mia chiesa", "natura", "silenzio"),
    ("Un fiore nel cemento mi ha ridato fiducia", "natura", "speranza"),
    ("Viaggiare serve a tornare diversi", "viaggio", "cambiamento"),
    ("La montagna ti ricorda quanto sei piccolo e quanto sei vivo", "natura", "consapevolezza"),
    ("Ogni valigia è una piccola promessa di ritorno", "viaggio", "casa"),
    ("Ho perso il treno e ho trovato una conversazione", "viaggio", "connessione"),
    ("Il cielo stellato mi consola più di mille parole", "notte", "natura"),
    ("Cammino per capire dove sto andando", "viaggio", "consapevolezza"),
    ("Le stagioni ci insegnano a cambiare senza vergogna", "natura", "cambiamento"),
    ("Il vento porta via quello che non serve", "natura", "liberta"),
    ("La strada è la casa di chi non sa fermarsi", "viaggio", "identita"),
    # --- lutto e gratitudine ---
    ("Chi ci ha lasciato vive nei gesti che ripetiamo", "lutto", "memoria"),
    ("Il lutto è amore che non ha più dove andare", "lutto", "amore"),
    ("Ringrazio ogni giorno per le cose che non noto più", "gratitudine", "consapevolezza"),
    ("Grazie a chi c'era quando non ero simpatico", "gratitudine", "amicizia"),
    ("Ho pianto poco al funerale e tanto tre mesi dopo", "lutto", "tempo"),
    ("Il nonno mi ha lasciato un orologio e la pazienza", "lutto", "famiglia"),
    ("Sono grato di essere ancora qui", "gratitudine", "forza"),
    ("Ogni sera conto tre cose belle prima di dormire", "gratitudine", "notte"),
    ("Ti scrivo anche se so che non leggerai", "lutto", "amore"),
    ("Dire grazie è il modo più semplice per non sentirsi soli", "gratitudine", "connessione"),
    # --- identità, cambiamento, forza, sfida ---
    ("Non so ancora chi sono, ma so chi non voglio essere", "identita", "consapevolezza"),
    ("Cambiare idea è una forma di crescita", "cambiamento", "apprendimento"),
    ("Sono stato tante persone e le porto tutte con me", "identita", "memoria"),
    ("La forza non è non cadere, è ricordare come si sale", "forza", "sfida"),
    ("Ogni fine è un cantiere aperto", "cambiamento", "speranza"),
    ("Mi sono riconosciuto nello specchio dopo anni", "identita", "consapevolezza"),
    ("La sfida più grande è essere gentili con sé stessi", "sfida", "perdono"),
    ("Non sono più quello di ieri e non mi manca", "cambiamento", "identita"),
    ("Chi resiste, prima o poi, respira", "forza", "speranza"),
    ("Trasformarsi fa male come crescere", "cambiamento", "forza"),
    ("Ho imparato a dire no e mi sono ritrovato", "identita", "liberta"),
    ("Ogni ostacolo è un maestro travestito", "sfida", "apprendimento"),
    ("Restare in piedi è già una vittoria", "forza", "sfida"),
    ("Mi hanno detto che non ce l'avrei fatta, e sono qui", "sfida", "coraggio"),
    # --- lavoro, rabbia, perdono, notte, cibo ---
    ("Lavoro tanto per non sentire quello che non voglio sentire", "lavoro", "paura"),
    ("Il lavoro mi ha dato un nome ma mi ha tolto il tempo", "lavoro", "tempo"),
    ("Sono stanco di essere forte per tutti", "rabbia", "forza"),
    ("La rabbia è il dolore che ha trovato una voce", "rabbia", "consapevolezza"),
    ("Ho urlato in macchina e mi è passata", "rabbia", "umorismo"),
    ("Perdonare non è dimenticare, è smettere di portare il peso", "perdono", "liberta"),
    ("Ho chiesto scusa e mi sono sentito più leggero", "perdono", "coraggio"),
    ("Mi arrabbio perché tengo a te", "rabbia", "amore"),
    ("Alle tre di notte i pensieri hanno la voce più alta", "notte", "paura"),
    ("La notte è l'ora in cui siamo tutti sinceri", "notte", "consapevolezza"),
    ("Cucinare per qualcuno è dire ti amo senza parole", "cibo", "amore"),
    ("Una pizza in compagnia risolve metà dei guai", "cibo", "amicizia"),
    ("Il pane appena sfornato è la prova che esiste qualcosa di buono", "cibo", "felicita"),
    ("Il caffè del mattino è il mio primo atto di fede", "cibo", "speranza"),
    ("Ho mangiato da solo e mi sono accorto di quanto manchi il rumore", "cibo", "solitudine"),
    # --- varie ---
    ("Le parole giuste arrivano sempre dopo", "silenzio", "tempo"),
    ("Ho scritto una lettera e non l'ho mai spedita", "memoria", "coraggio"),
    ("Vorrei essere ricordato per come ho fatto sentire gli altri", "identita", "connessione"),
    ("Mi piaci quando sei te stesso senza accorgertene", "amore", "identita"),
    ("Il primo giorno di scuola ho capito che il mondo era grande", "apprendimento", "paura"),
    ("Siamo tutti stelle che credono di essere sole", "connessione", "notte"),
    ("Ci vuole un villaggio per crescere un adulto", "connessione", "famiglia"),
    ("Non siamo mai davvero soli, siamo solo distratti", "solitudine", "consapevolezza"),
    ("Ho salutato il mare prima di partire, come si fa con un amico", "mare", "viaggio"),
    ("Il bello dei vecchi è che non hanno più niente da dimostrare", "tempo", "liberta"),
    ("Sbaglio, rido, riprovo", "sfida", "umorismo"),
    ("Il futuro è un foglio bianco che mi fa venire l'ansia e il sorriso", "speranza", "paura"),
    ("Una carezza al momento giusto vale più di un discorso", "amore", "silenzio"),
    ("L'anima ha bisogno di rumore e di quiete, in dosi uguali", "silenzio", "musica"),
    ("Chi ama il mare non ha mai davvero paura", "mare", "coraggio"),
    ("Ci sono giorni in cui basta esserci", "forza", "consapevolezza"),
    ("Le ferite fanno luce, se le lasci aperte alla verità", "coraggio", "perdono"),
    ("Tra tutto quello che finisce, resta quello che abbiamo dato", "gratitudine", "lutto"),
    # ===== 30 NUOVI TAG =====
    # --- bellezza ---
    ("La bellezza è un modo di fare attenzione", "bellezza", "consapevolezza"),
    ("Ho trovato bello un muro scrostato e non so perché", "bellezza", "citta"),
    ("C'è più bellezza nei difetti che nelle cose perfette", "bellezza", "identita"),
    ("Una persona che ride senza accorgersene è la cosa più bella che ho visto oggi", "bellezza", "felicita"),
    ("Il tramonto non chiede il permesso a nessuno per essere bello", "bellezza", "sole"),
    # --- curiosita ---
    ("Da grande voglio restare curioso come a sei anni", "curiosita", "infanzia"),
    ("Ogni domanda è una porta con la maniglia dalla mia parte", "curiosita", "coraggio"),
    ("Ho aperto un libro a caso e ho cambiato idea su tutto", "curiosita", "libri"),
    ("La curiosità mi ha portato lontano e mai in un posto sbagliato", "curiosita", "viaggio"),
    ("Chiedere perché è il modo più onesto di voler bene", "curiosita", "amore"),
    # --- pazienza ---
    ("La pazienza è amore che sa aspettare", "pazienza", "amore"),
    ("Il seme non si tira per farlo crescere", "pazienza", "natura"),
    ("Ho imparato ad aspettare senza fingere che non mi costi", "pazienza", "attesa"),
    ("Le cose belle arrivano a passo lento", "pazienza", "tempo"),
    ("Con la pazienza si scioglie anche il nodo più stretto", "pazienza", "forza"),
    # --- fiducia ---
    ("Fidarsi è lasciare la porta socchiusa", "fiducia", "coraggio"),
    ("Ho affidato il mio segreto più pesante a chi non lo ha mai ripetuto", "fiducia", "segreto"),
    ("La fiducia si costruisce a mattoncini e crolla con un sussurro", "fiducia", "paura"),
    ("Mi fido del mare più che degli uomini", "fiducia", "mare"),
    ("Ho smesso di controllare il telefono e ho ricominciato a respirare", "fiducia", "liberta"),
    # --- fede ---
    ("Credere è accendere una candela senza sapere se qualcuno la vede", "fede", "speranza"),
    ("Non so in cosa credo, ma so che credo", "fede", "consapevolezza"),
    ("Mia nonna pregava per tutti, anche per chi non lo sapeva", "fede", "famiglia"),
    ("Nel silenzio di una chiesa vuota ho sentito casa", "fede", "silenzio"),
    ("La fede è un salto con la rete fatta di persone", "fede", "connessione"),
    # --- desiderio ---
    ("Desiderare è già un modo di essere vivi", "desiderio", "felicita"),
    ("Vorrei tutto e mi basterebbe una sera con te", "desiderio", "amore"),
    ("Il desiderio è una finestra aperta sul futuro", "desiderio", "sogno"),
    ("Ho desiderato una vita diversa e ho scoperto di averne già una", "desiderio", "gratitudine"),
    ("Alcune cose le voglio solo perché non le posso avere", "desiderio", "identita"),
    # --- gelosia ---
    ("La gelosia è paura travestita da amore", "gelosia", "paura"),
    ("Ho invidiato la tua leggerezza per anni", "gelosia", "identita"),
    ("Ho chiuso il telefono per non guardare dove sei", "gelosia", "amore"),
    ("Essere gelosi è ammettere di avere qualcosa da perdere", "gelosia", "consapevolezza"),
    ("Mi confronto con tutti e perdo sempre con me stesso", "gelosia", "vergogna"),
    # --- tristezza ---
    ("La tristezza è una stanza in cui prima o poi si accende la luce", "tristezza", "speranza"),
    ("Oggi mi manchi senza motivo", "tristezza", "nostalgia"),
    ("Piango poco ma quando succede è per cose belle", "tristezza", "gratitudine"),
    ("Ci sono giorni grigi che insegnano a distinguere i colori", "tristezza", "pioggia"),
    ("Non tutte le tristezze hanno bisogno di una spiegazione", "tristezza", "silenzio"),
    # --- ansia ---
    ("L'ansia è la voce di chi vuole proteggermi e non sa come", "ansia", "consapevolezza"),
    ("Respiro contando fino a quattro e il mondo si ferma un attimo", "ansia", "pace"),
    ("Il domani mi pesa più dell'oggi", "ansia", "tempo"),
    ("Ho l'ansia che qualcosa vada bene e mi sembra assurdo", "ansia", "paura"),
    ("Quando tutto corre, mi siedo e guardo il cielo", "ansia", "sole"),
    # --- pace ---
    ("La pace non è assenza di rumore ma di guerra dentro", "pace", "silenzio"),
    ("Ho fatto pace con il mio riflesso", "pace", "identita"),
    ("Basta un pomeriggio di sole sul balcone per riconciliarmi col mondo", "pace", "sole"),
    ("Ho smesso di combattere e ho vinto qualcosa", "pace", "forza"),
    ("La pace comincia da una tazza calda e da un telefono spento", "pace", "cibo"),
    # --- vergogna ---
    ("Mi vergognavo di piangere e ora mi vergogno di non averlo fatto", "vergogna", "tristezza"),
    ("La vergogna sparisce quando la racconti a qualcuno", "vergogna", "connessione"),
    ("Ho nascosto per anni quello che ero", "vergogna", "identita"),
    ("Le mie cicatrici sono pezzi di storia, non di colpa", "vergogna", "perdono"),
    ("Ridere dei propri errori toglie loro il potere", "vergogna", "umorismo"),
    # --- orgoglio ---
    ("L'orgoglio è la scusa più pesante che porto in tasca", "orgoglio", "perdono"),
    ("Sono fiero di non essermi arreso", "orgoglio", "forza"),
    ("Mi sono inchinato solo davanti al mare", "orgoglio", "mare"),
    ("Ho messo da parte l'orgoglio e ho chiamato", "orgoglio", "amicizia"),
    ("Napoli mi ha insegnato a camminare a testa alta", "orgoglio", "napoli"),
    # --- poesia ---
    ("Una poesia è un pensiero che ha imparato a respirare", "poesia", "creativita"),
    ("Scrivo versi sui tovaglioli dei bar", "poesia", "citta"),
    ("Ogni verso è una piccola preghiera laica", "poesia", "fede"),
    ("La poesia è quello che resta quando togli tutto il superfluo", "poesia", "silenzio"),
    ("Ho letto una riga e mi sono sentito capito", "poesia", "libri"),
    # --- luna ---
    ("La luna è l'unica che non mi fa domande", "luna", "notte"),
    ("Guardiamo la stessa luna da due città diverse", "luna", "amore"),
    ("Anche la luna ha bisogno di sparire per tornare piena", "luna", "cambiamento"),
    ("Sotto la luna le paure sembrano più piccole", "luna", "paura"),
    ("Il mare e la luna hanno un patto che io non capirò mai", "luna", "mare"),
    # --- pioggia ---
    ("Amo il rumore della pioggia sui vetri quando sono al sicuro", "pioggia", "casa"),
    ("Ho camminato sotto la pioggia senza ombrello e mi sono sentito vivo", "pioggia", "liberta"),
    ("Dopo la pioggia la città sembra lavata da capo", "pioggia", "citta"),
    ("La pioggia porta via anche le lacrime", "pioggia", "tristezza"),
    ("Un temporale mi ha riportato dalla nonna", "pioggia", "memoria"),
    # --- sole ---
    ("Il sole del mattino è una carezza gratis", "sole", "gratitudine"),
    ("Mi basta un raggio sul viso per ricominciare", "sole", "speranza"),
    ("D'estate il tempo si scioglie come un gelato", "sole", "tempo"),
    ("Al sole tutti i problemi sembrano più leggeri", "sole", "felicita"),
    ("Ho seguito il sole finché non ho trovato casa", "sole", "viaggio"),
    # --- infanzia ---
    ("L'infanzia è il paese da cui tutti veniamo", "infanzia", "memoria"),
    ("Da piccolo credevo che le nuvole fossero fatte di cotone", "infanzia", "sogno"),
    ("Giocavo per strada finché mia madre non chiamava", "infanzia", "gioco"),
    ("Il bambino che ero mi guarda e mi chiede se sono felice", "infanzia", "identita"),
    ("Vorrei tornare a quando bastava un gelato per essere contento", "infanzia", "nostalgia"),
    # --- vecchiaia ---
    ("Invecchiare è diventare la persona che vedevo quando ero piccolo", "vecchiaia", "tempo"),
    ("Le rughe sono la mappa dei posti dove ho riso", "vecchiaia", "felicita"),
    ("Mio nonno raccontava sempre la stessa storia e io non mi stancavo mai", "vecchiaia", "famiglia"),
    ("Da vecchi si capisce che quasi niente era così grave", "vecchiaia", "consapevolezza"),
    ("Vorrei invecchiare con qualcuno che mi ricordi chi sono", "vecchiaia", "amore"),
    # --- corpo ---
    ("Il mio corpo si ricorda cose che io ho dimenticato", "corpo", "memoria"),
    ("Ho imparato ad ascoltare la stanchezza prima che gridi", "corpo", "consapevolezza"),
    ("Camminare è il mio modo di pregare", "corpo", "viaggio"),
    ("Mi guardo allo specchio e provo a volermi bene", "corpo", "identita"),
    ("Il corpo sa quando è ora di riposare, la testa fa finta di no", "corpo", "pazienza"),
    # --- abbraccio ---
    ("Un abbraccio lungo dice quello che le parole non trovano", "abbraccio", "silenzio"),
    ("Ho bisogno di un abbraccio e non so come chiederlo", "abbraccio", "solitudine"),
    ("L'abbraccio di mio padre era la casa più sicura del mondo", "abbraccio", "famiglia"),
    ("Ci siamo abbracciati sulla banchina e il treno ha aspettato", "abbraccio", "addio"),
    ("Un abbraccio al momento giusto vale più di mille consigli", "abbraccio", "amicizia"),
    # --- promessa ---
    ("Ho promesso e ho mantenuto, e nessuno lo ha saputo", "promessa", "orgoglio"),
    ("Le promesse piccole tengono in piedi il mondo", "promessa", "fiducia"),
    ("Ti ho promesso il mare e ti porterò il mare", "promessa", "mare"),
    ("Non fare promesse che non sai mantenere, ma fanne di coraggiose", "promessa", "coraggio"),
    ("L'ho promesso a mio nonno e ogni volta ci penso", "promessa", "lutto"),
    # --- segreto ---
    ("Custodisco un segreto che pesa quanto una pietra calda", "segreto", "silenzio"),
    ("Tutti hanno una stanza chiusa dentro", "segreto", "identita"),
    ("Ho detto il mio segreto a un estraneo in treno", "segreto", "viaggio"),
    ("Il segreto più difficile è quello che tieni da te stesso", "segreto", "consapevolezza"),
    ("Certe cose si dicono solo di notte", "segreto", "notte"),
    # --- verita ---
    ("Dire la verità costa una volta, mentire costa sempre", "verita", "coraggio"),
    ("La verità è che mi manchi e non voglio dirtelo", "verita", "amore"),
    ("Ho scoperto la verità e ho preferito restare a guardarla", "verita", "consapevolezza"),
    ("Nessuno è più sincero di un bambino e di un ubriaco", "verita", "umorismo"),
    ("La verità libera anche quando fa male", "verita", "liberta"),
    # --- destino ---
    ("Il destino è un filo che si annoda dove meno te lo aspetti", "destino", "connessione"),
    ("Non credo al destino, ma ho incontrato te", "destino", "amore"),
    ("Ogni strada sbagliata mi ha portato dove dovevo essere", "destino", "viaggio"),
    ("Forse tutto ha un senso e io sono solo miope", "destino", "fede"),
    ("Il caso è il destino quando è di buon umore", "destino", "umorismo"),
    # --- attesa ---
    ("Aspetto una telefonata da tre giorni", "attesa", "ansia"),
    ("Il tempo dell'attesa è più lungo di quello dell'incontro", "attesa", "tempo"),
    ("Ho aspettato tutta la vita e non è stato tempo perso", "attesa", "gratitudine"),
    ("Alla stazione tutti aspettano qualcuno o qualcosa", "attesa", "viaggio"),
    ("L'attesa è metà della festa", "attesa", "felicita"),
    # --- addio ---
    ("Dire addio è più facile che restare", "addio", "coraggio"),
    ("Non ci siamo salutati e questo mi pesa ogni giorno", "addio", "lutto"),
    ("Ogni addio è un arrivederci che non ha il coraggio di dirsi", "addio", "speranza"),
    ("Ho salutato la mia città con un caffè in mano", "addio", "napoli"),
    ("Gli addii fatti bene lasciano più amore di mille incontri", "addio", "amore"),
    # --- ritorno ---
    ("Tornare è un modo di conoscere per la prima volta", "ritorno", "consapevolezza"),
    ("Ogni ritorno ha il sapore del sugo di mia madre", "ritorno", "cibo"),
    ("Il treno del ritorno è sempre più lento", "ritorno", "viaggio"),
    ("Sono tornato e tutto era uguale tranne me", "ritorno", "cambiamento"),
    ("Il porto è bello solo per chi è stato in mare", "ritorno", "mare"),
    # --- citta ---
    ("La città di notte parla piano", "citta", "notte"),
    ("Ho imparato a camminare tra la folla senza sentirmi solo", "citta", "solitudine"),
    ("Ogni strada del mio quartiere ha una storia mia", "citta", "memoria"),
    ("Le luci dei palazzi sono tante finestre su vite che non conoscerò", "citta", "connessione"),
    ("Amo la mia città anche quando la odio", "citta", "amore"),
    # --- animali ---
    ("Il mio cane mi aspetta ogni sera e io ci torno anche per lui", "animali", "casa"),
    ("Un gatto mi ha insegnato a stare fermo", "animali", "pazienza"),
    ("Gli animali non mentono, per questo li amo", "animali", "verita"),
    ("I gabbiani sul lungomare ridono di noi", "animali", "umorismo"),
    ("Guardo le formiche e penso che nessuno è davvero solo", "animali", "natura"),
    # --- libri ---
    ("Un libro è una porta che si apre sempre nel momento giusto", "libri", "viaggio"),
    ("Ho riletto il libro della mia infanzia e sono tornato bambino", "libri", "infanzia"),
    ("Leggere di notte è la mia forma di compagnia", "libri", "notte"),
    ("Ogni pagina sottolineata è un pezzo di me", "libri", "identita"),
    ("Una biblioteca è un posto dove il silenzio è pieno", "libri", "silenzio"),
    # ===== ALTRE FRASI PER LA STELLA "AMORE" =====
    ("Amare è scegliere ogni giorno la stessa persona", "amore", "fiducia"),
    ("Ho imparato cos'è l'amore da come mi hai portato il caffè", "amore", "cibo"),
    ("Ti amo nei dettagli: la tazza che usi, il modo in cui ridi", "amore", "bellezza"),
    ("L'amore non fa rumore, sta seduto accanto a te", "amore", "silenzio"),
    ("Il primo amore non si dimentica, si impara a conoscere", "amore", "memoria"),
    ("Con te anche il lunedì ha un altro sapore", "amore", "felicita"),
    ("Ti amo come il mare ama la riva: tornando sempre", "amore", "ritorno"),
    ("L'amore ha bisogno di coraggio più che di parole", "amore", "coraggio"),
    ("Ho amato senza essere ricambiato e sono cresciuto lo stesso", "amore", "forza"),
    ("L'amore è una lingua che si impara sbagliando", "amore", "apprendimento"),
    ("Vorrei portarti a Napoli e farti innamorare della mia città", "amore", "napoli"),
    ("Nessuna distanza è troppo grande quando qualcuno ti pensa", "amore", "viaggio"),
    ("Amare è anche lasciare andare", "amore", "liberta"),
    ("Ti ho scritto una canzone e non ho mai avuto il coraggio di cantartela", "amore", "musica"),
    ("Sotto la pioggia mi hai dato il tuo cappotto e io ho capito", "amore", "pioggia"),
    ("Il nostro amore è fatto di piccole promesse mantenute", "amore", "promessa"),
    ("L'amore è ridere insieme anche quando tutto va storto", "amore", "umorismo"),
    ("Ti penso quando il mondo tace e anche quando fa rumore", "amore", "solitudine"),
    # ===== 45 TAG IN PIU', per coprire tutta la costellazione nascosta =====
    ("Ogni domanda che mi faccio e' gia' meta' di una scoperta", "scoperta", "curiosita"),
    ("Ho scoperto una parte di me che non sapevo di avere", "scoperta", "identita"),
    ("Le scoperte piu' belle arrivano quando non le cerco", "scoperta", "sorpresa"),
    ("Mi fermo spesso solo per guardare quanto e' strano tutto", "meraviglia", "consapevolezza"),
    ("Un cielo pieno di stelle mi lascia senza parole ogni volta", "meraviglia", "notte"),
    ("La meraviglia e' l'unica cosa che non invecchia mai", "meraviglia", "infanzia"),
    ("Sono rimasto a bocca aperta davanti a una cosa piccolissima", "stupore", "bellezza"),
    ("Lo stupore e' il primo passo prima di ogni domanda vera", "stupore", "curiosita"),
    ("Mi stupisco ancora di quanto siamo fatti di poco", "stupore", "corpo"),
    ("Ho trovato il mio equilibrio tra il fare e il lasciar andare", "equilibrio", "pace"),
    ("L'equilibrio non e' stare fermi, e' cadere piano", "equilibrio", "forza"),
    ("Cerco l'equilibrio come un funambolo senza rete e senza paura", "equilibrio", "coraggio"),
    ("Le mie radici sono piu' forti di quanto pensassi", "radici", "famiglia"),
    ("Sono partito per trovarmi e ho ritrovato le mie radici", "radici", "viaggio"),
    ("Un albero con radici profonde non teme il vento", "radici", "natura"),
    ("Guardo l'orizzonte e mi sembra sempre un po' piu' vicino", "orizzonte", "speranza"),
    ("Ogni orizzonte nuovo mi fa sentire piu' piccolo e piu' libero", "orizzonte", "liberta"),
    ("Il mare e l'orizzonte si tengono per mano da sempre", "orizzonte", "mare"),
    ("La semplicita' e' la cosa piu' difficile da raggiungere", "semplicita", "consapevolezza"),
    ("Mi basta poco, e l'ho capito tardi", "semplicita", "gratitudine"),
    ("Le cose semplici sono quelle che restano", "semplicita", "tempo"),
    ("La generosita' vera non si fa notare", "generosita", "silenzio"),
    ("Ho ricevuto piu' di quanto abbia mai dato, e mi pesa un po'", "generosita", "gratitudine"),
    ("Dare senza aspettarsi niente e' la lezione piu' difficile", "generosita", "amore"),
    ("Capire qualcuno e' il regalo piu' grande che posso fare", "empatia", "connessione"),
    ("Mi sono messo nei tuoi panni e ho smesso di giudicare", "empatia", "perdono"),
    ("L'empatia e' sentire senza dover spiegare come", "empatia", "silenzio"),
    ("Ascoltare davvero e' piu' raro di parlare bene", "ascolto", "silenzio"),
    ("Ho imparato ad ascoltare anche quello che non si dice", "ascolto", "amicizia"),
    ("Il miglior regalo che ho fatto e' stato stare zitto e ascoltare", "ascolto", "amore"),
    ("Il presente e' l'unico posto dove sono mai stato davvero", "presente", "consapevolezza"),
    ("Smetto di correre e il presente mi viene incontro", "presente", "pace"),
    ("Vivo nel presente anche se il passato bussa spesso", "presente", "memoria"),
    ("Ogni inizio porta con se' la paura di non essere pronto", "inizio", "paura"),
    ("Ho ricominciato cosi' tante volte che ormai ci so fare", "inizio", "forza"),
    ("Un nuovo inizio e' solo una fine vista da un'altra parte", "inizio", "cambiamento"),
    ("Sono rinato ogni volta che ho toccato il fondo", "rinascita", "forza"),
    ("La rinascita non cancella le cicatrici, le illumina", "rinascita", "coraggio"),
    ("Dopo l'inverno piu' lungo sono rinato con la primavera", "rinascita", "speranza"),
    ("La resilienza e' piegarsi senza dimenticare come si sta dritti", "resilienza", "forza"),
    ("Ho imparato a resistere senza indurirmi", "resilienza", "consapevolezza"),
    ("Resisto non perche' sono forte, ma perche' non ho altra scelta", "resilienza", "coraggio"),
    ("Ho smesso di portare pesi che non erano miei", "leggerezza", "liberta"),
    ("La leggerezza non e' superficialita', e' saper lasciar cadere", "leggerezza", "pace"),
    ("Mi piace chi sa essere leggero anche nei giorni pesanti", "leggerezza", "umorismo"),
    ("Sotto ogni battuta c'e' una profondita' che non mostro a tutti", "profondita", "umorismo"),
    ("Cerco profondita' nelle conversazioni piccole", "profondita", "ascolto"),
    ("Le persone profonde parlano piano", "profondita", "silenzio"),
    ("Mi piace tutto cio' che non si spiega del tutto", "mistero", "curiosita"),
    ("C'e' un mistero in ogni persona che credo di conoscere bene", "mistero", "identita"),
    ("Il mistero piu' grande sono io per me stesso", "mistero", "consapevolezza"),
    ("Certe sere la citta' sembra avere un po' di magia addosso", "magia", "citta"),
    ("Ho smesso di cercare la magia e ho iniziato a notarla", "magia", "gratitudine"),
    ("C'e' magia in due persone che si capiscono senza parlare", "magia", "amore"),
    ("Cerco l'armonia tra quello che sento e quello che faccio", "armonia", "consapevolezza"),
    ("L'armonia non e' l'assenza di conflitto, e' saperlo attraversare", "armonia", "pace"),
    ("In famiglia l'armonia si costruisce un pranzo alla volta", "armonia", "famiglia"),
    ("Dal caos della mia stanza nasce sempre qualcosa di buono", "caos", "creativita"),
    ("Mi sento a casa nel caos piu' che nell'ordine perfetto", "caos", "casa"),
    ("Il caos di Napoli ha una logica che solo chi ci vive capisce", "caos", "napoli"),
    ("Mi sono ribellato alle regole che non capivo", "ribellione", "coraggio"),
    ("La ribellione piu' grande e' restare gentili", "ribellione", "gentilezza"),
    ("Da giovane la ribellione era l'unico modo che conoscevo per esistere", "ribellione", "identita"),
    ("L'umilta' e' sapere quanto poco so davvero", "umilta", "consapevolezza"),
    ("Ho imparato di piu' da chi non aveva bisogno di dimostrare niente", "umilta", "apprendimento"),
    ("La vera forza si riconosce dall'umilta'", "umilta", "forza"),
    ("Ho difeso la mia dignita' anche quando mi costava caro", "dignita", "coraggio"),
    ("La dignita' non si negozia, nemmeno per amore", "dignita", "amore"),
    ("Si puo' perdere tutto tranne la dignita'", "dignita", "forza"),
    ("Preferisco un'onesta' scomoda a una bugia comoda", "onesta", "verita"),
    ("L'onesta' con se stessi e' la piu' difficile da mantenere", "onesta", "consapevolezza"),
    ("Ho scelto l'onesta' anche quando il silenzio sarebbe stato piu' facile", "onesta", "coraggio"),
    ("La lealta' si vede nei momenti in cui nessuno guarda", "lealta", "amicizia"),
    ("Sono rimasto leale a chi non se lo aspettava piu'", "lealta", "fiducia"),
    ("La lealta' e' una promessa che si rinnova senza dirlo", "lealta", "promessa"),
    ("Siamo complici in un modo che non so spiegare a nessuno", "complicita", "amicizia"),
    ("Basta uno sguardo tra noi e capiamo tutto", "complicita", "connessione"),
    ("La complicita' vera resiste anche al silenzio", "complicita", "silenzio"),
    ("La passione mi ha fatto fare scelte che la ragione non avrebbe fatto", "passione", "coraggio"),
    ("Metto passione anche nelle cose piccole, mi fa sentire vivo", "passione", "felicita"),
    ("La passione senza costanza e' solo un fuoco che si spegne presto", "passione", "pazienza"),
    ("C'e' una dolcezza nelle persone che hanno sofferto tanto", "dolcezza", "forza"),
    ("Mi piace la dolcezza di chi non ha fretta di niente", "dolcezza", "pazienza"),
    ("La dolcezza e' una forma silenziosa di coraggio", "dolcezza", "coraggio"),
    ("Una malinconia dolce mi accompagna nelle giornate di pioggia", "malinconia", "pioggia"),
    ("La malinconia non e' tristezza, e' amore per cio' che e' stato", "malinconia", "nostalgia"),
    ("Certe canzoni mi mettono una malinconia che quasi mi piace", "malinconia", "musica"),
    ("Ho sentito euforia pura correndo senza meta sotto la pioggia", "euforia", "liberta"),
    ("L'euforia di un abbraccio dopo tanto tempo non si dimentica", "euforia", "abbraccio"),
    ("Ballare fino a tardi mi riempie di un'euforia semplice", "euforia", "danza"),
    ("Riconosco la stanchezza che non si risolve dormendo", "stanchezza", "lavoro"),
    ("Sono stanco in un modo che nessuna vacanza aggiusta del tutto", "stanchezza", "corpo"),
    ("Ho imparato a fermarmi prima che la stanchezza decida per me", "stanchezza", "consapevolezza"),
    ("Il riposo non e' pigrizia, e' manutenzione dell'anima", "riposo", "pace"),
    ("Mi concedo il riposo come un atto di rispetto verso me stesso", "riposo", "gratitudine"),
    ("Un pomeriggio di riposo vale piu' di mille produttivita'", "riposo", "felicita"),
    ("Il movimento del corpo mi scioglie i pensieri", "movimento", "corpo"),
    ("Mi piace il movimento delle citta' viste dall'alto", "movimento", "citta"),
    ("Il movimento delle onde mi calma sempre", "movimento", "mare"),
    ("Ho scoperto che so ancora ballare, anche senza musica", "danza", "liberta"),
    ("La danza e' l'unica lingua che il mio corpo parla bene", "danza", "corpo"),
    ("Abbiamo ballato in cucina come se nessuno ci guardasse", "danza", "amore"),
    ("Un teatro vuoto ha una magia tutta sua", "teatro", "silenzio"),
    ("Recitare mi ha insegnato a essere piu' sincero nella vita vera", "teatro", "verita"),
    ("A teatro ho pianto per una storia che non era la mia", "teatro", "empatia"),
    ("Un film visto da solo puo' sembrare una lettera scritta per me", "cinema", "solitudine"),
    ("Il cinema mi ha insegnato a sognare a occhi aperti", "cinema", "sogno"),
    ("Siamo usciti dal cinema e il mondo sembrava diverso", "cinema", "amore"),
    ("Scrivere e' il modo in cui ordino il disordine che ho dentro", "scrittura", "caos"),
    ("Ho scritto per anni solo per me, poi ho avuto il coraggio di mostrarlo", "scrittura", "coraggio"),
    ("La scrittura mi lascia piu' leggero ogni volta", "scrittura", "leggerezza"),
    ("Dipingere e' l'unico momento in cui non giudico quello che faccio", "pittura", "creativita"),
    ("Ho scoperto la pittura tardi e mi dispiace solo per il tempo perso", "pittura", "tempo"),
    ("Un quadro non finito mi insegna la pazienza", "pittura", "pazienza"),
    ("In montagna il respiro si fa piu' vero", "montagna", "corpo"),
    ("Dalla cima della montagna i problemi sembrano cosi' piccoli", "montagna", "consapevolezza"),
    ("Amo la montagna d'inverno, il silenzio bianco che porta", "montagna", "silenzio"),
    ("Il deserto mi ha insegnato quanto poco serve per essere felici", "deserto", "semplicita"),
    ("Nel deserto il silenzio ha un peso che non avevo mai sentito", "deserto", "silenzio"),
    ("Attraversare il deserto da soli cambia il modo di guardare tutto", "deserto", "viaggio"),
    ("Mi siedo sempre vicino a un fiume quando devo decidere qualcosa", "fiume", "attesa"),
    ("Il fiume non torna mai indietro, e un po' lo invidio", "fiume", "tempo"),
    ("Ho imparato a lasciar scorrere le cose come fa un fiume", "fiume", "liberta"),
    ("Il vento mi porta sempre pensieri che non sapevo di avere", "vento", "pensiero"),
    ("Cammino controvento quando ho bisogno di sentirmi vivo", "vento", "coraggio"),
    ("Il vento di Napoli sa di mare anche lontano dal mare", "vento", "napoli"),
    ("La prima neve mi fa sempre tornare bambino", "neve", "infanzia"),
    ("Sotto la neve tutto sembra piu' silenzioso e piu' onesto", "neve", "silenzio"),
    ("Abbiamo fatto un pupazzo di neve e per un giorno niente altro contava", "neve", "famiglia"),
    ("L'autunno mi mette addosso una calma malinconica", "autunno", "malinconia"),
    ("Le foglie che cadono mi ricordano che lasciar andare e' naturale", "autunno", "cambiamento"),
    ("Preferisco l'autunno a ogni altra stagione, non so spiegare perche'", "autunno", "identita"),
    ("L'estate ha il sapore delle cose fatte senza pensarci troppo", "estate", "liberta"),
    ("Le sere d'estate con gli amici valgono un intero anno", "estate", "amicizia"),
    ("D'estate il tempo rallenta e io con lui", "estate", "tempo"),
    # --- nuovi tag (per rendere leggibile la costellazione) ---
    ("Il cielo di Napoli la sera sembra dipinto da qualcuno che ci vuole bene", "cielo", "napoli"),
    ("Guardo il cielo quando non so cosa dire", "cielo", "silenzio"),
    ("Ogni stella che vedo è un tempo che non esiste più", "stelle", "tempo"),
    ("Contavamo le stelle per non contare i problemi", "stelle", "infanzia"),
    ("Ogni alba è una seconda possibilità senza scartoffie", "alba", "speranza"),
    ("All'alba la città è ancora mia", "alba", "citta"),
    ("Il tramonto non chiede il permesso per essere bellissimo", "tramonto", "bellezza"),
    ("Abbiamo guardato il tramonto senza dirci niente, ed era tutto", "tramonto", "amore"),
    ("Dopo la tempesta il mondo profuma di pulito", "tempesta", "rinascita"),
    ("Ho dentro una tempesta che non fa rumore", "tempesta", "ansia"),
    ("Il fuoco del camino era l'unica televisione di casa", "fuoco", "famiglia"),
    ("Dentro ho un fuoco che non sa se scaldare o bruciare", "fuoco", "passione"),
    ("L'acqua prende la forma di ciò che la contiene, vorrei imparare", "acqua", "equilibrio"),
    ("Mi lavo il viso e sembra di ricominciare", "acqua", "inizio"),
    ("La terra sotto i piedi nudi dice la verità", "terra", "verita"),
    ("Da dove vengo la terra è rossa e tiene stretti i suoi figli", "terra", "radici"),
    ("L'albero davanti a casa conosce tutti i miei segreti", "albero", "segreto"),
    ("Pianto un albero sapendo che non ne vedrò l'ombra", "albero", "generosita"),
    ("Mi hai regalato un fiore e ho capito di esistere", "fiore", "gentilezza"),
    ("I fiori nascono anche dove nessuno li aspetta", "fiore", "resilienza"),
    ("Nel giardino di mia nonna il tempo si prende una pausa", "giardino", "nonni"),
    ("Curare un giardino è imparare ad aspettare", "giardino", "pazienza"),
    ("Una strada deserta di notte mi parla più di mille discorsi", "strada", "notte"),
    ("Ogni strada che non ho preso mi accompagna lo stesso", "strada", "scelta"),
    ("Il treno parte e io resto, ancora una volta", "treno", "addio"),
    ("Sul treno ho capito che non scappavo, tornavo", "treno", "ritorno"),
    ("Negli aeroporti tutti hanno la faccia di chi sta per cambiare", "aeroporto", "cambiamento"),
    ("Ho salutato qualcuno al gate senza sapere che era l'ultima volta", "aeroporto", "addio"),
    ("Dalla finestra vedo la vita degli altri e mi consolo", "finestra", "solitudine"),
    ("Apro la finestra e lascio entrare tutto, anche il rumore", "finestra", "liberta"),
    ("C'è una porta che non ho il coraggio di aprire", "porta", "coraggio"),
    ("Lascio la porta socchiusa, nel caso tornassi", "porta", "attesa"),
    ("Lo specchio mi guarda come se mi conoscesse da sempre", "specchio", "identita"),
    ("Ho smesso di cercare nello specchio quello che non c'è", "specchio", "pace"),
    ("La mia ombra è l'unica che non mi ha mai lasciato", "ombra", "solitudine"),
    ("Ho paura della mia ombra solo quando smetto di guardarla", "ombra", "paura"),
    ("Basta una candela per cambiare il senso di una stanza", "luce", "magia"),
    ("La luce che cerco è già dentro, ma sono sempre troppo veloce", "luce", "consapevolezza"),
    ("Nel buio ho imparato a fidarmi delle mani", "buio", "fiducia"),
    ("Il buio non mi fa paura, mi fanno paura le luci accese sui pensieri", "buio", "ansia"),
    ("Dormire è l'unico modo di perdonarmi", "sonno", "perdono"),
    ("Il sonno dei bambini è la cosa più vicina alla pace", "sonno", "infanzia"),
    ("Da anni lo stesso incubo mi visita, ormai gli preparo il caffè", "incubo", "umorismo"),
    ("L'incubo finisce quando decido di guardarlo in faccia", "incubo", "coraggio"),
    ("Il risveglio è il momento in cui mi dimentico di essere triste", "risveglio", "tristezza"),
    ("Ogni mattina mi risveglio un po' diverso e nessuno se ne accorge", "risveglio", "cambiamento"),
    ("Il caffè del mattino è l'unica preghiera che non salto", "caffe", "fede"),
    ("Un caffè in due vale più di una cena da soli", "caffe", "amicizia"),
    ("Il profumo del pane appena sfornato è casa", "pane", "casa"),
    ("Spezzare il pane insieme è il modo più antico di fare pace", "pane", "pace"),
    ("Un bicchiere di vino e le storie si fanno vere", "vino", "verita"),
    ("Mio nonno beveva un bicchiere e raccontava la sua guerra", "vino", "nonni"),
    ("In cucina ho imparato che l'amore è una questione di tempi", "cucina", "tempo"),
    ("Cucinare per qualcuno è dire ti voglio bene senza parole", "cucina", "amore"),
    ("Intorno a una tavola nessuno è davvero solo", "tavola", "solitudine"),
    ("La tavola apparecchiata è una promessa di ritorno", "tavola", "promessa"),
    ("Il regalo più bello è stato un'ora del tuo tempo", "regalo", "tempo"),
    ("Regalo cose per non dover dire quanto mi manchi", "regalo", "nostalgia"),
    ("Alle feste mi sento sempre un po' ospite di me stesso", "festa", "identita"),
    ("Dopo la festa resta la parte più sincera della serata", "festa", "silenzio"),
    ("Ogni compleanno è un conto alla rovescia che preferisco ignorare", "compleanno", "vecchiaia"),
    ("Per il mio compleanno ho desiderato che nulla cambiasse", "compleanno", "desiderio"),
    ("A Natale ci sono sempre sedie vuote che nessuno sposta", "natale", "lutto"),
    ("Il Natale è l'unica volta in cui tutti torniamo bambini", "natale", "famiglia"),
    ("A scuola ho imparato tutto tranne ciò che mi serviva", "scuola", "apprendimento"),
    ("Il primo giorno di scuola ha ancora il profumo dei quaderni nuovi", "scuola", "infanzia"),
    ("Un bravo maestro ti insegna a dubitare di lui", "maestro", "curiosita"),
    ("Il mio maestro non ha mai alzato la voce, e lo ascoltavano tutti", "maestro", "ascolto"),
    ("Prima di un esame il mondo si riduce a una stanza", "esame", "ansia"),
    ("Ho passato l'esame più importante lontano da ogni aula", "esame", "sfida"),
    ("Ho fallito e il mondo è andato avanti, che sollievo", "fallimento", "leggerezza"),
    ("Dal fallimento si impara a camminare con più cura", "fallimento", "umilta"),
    ("Il successo non mi ha reso felice, solo più solo", "successo", "solitudine"),
    ("Non misuro il successo, misuro quante volte ho riso oggi", "successo", "felicita"),
    ("Il denaro compra tutto tranne il tempo che ho già venduto", "denaro", "tempo"),
    ("Con pochi soldi ho imparato a distinguere le cose necessarie", "denaro", "semplicita"),
    ("La povertà mi ha insegnato la dignità prima delle parole", "poverta", "dignita"),
    ("Siamo stati poveri, ma non ci è mai mancata la tavola", "poverta", "famiglia"),
    ("Ogni sacrificio fatto per amore pesa meno di quello fatto per dovere", "sacrificio", "amore"),
    ("Mia madre ha sacrificato i suoi sogni senza mai nominarli", "sacrificio", "sogno"),
    ("Essere adulti è accorgersi che nessuno verrà a decidere per te", "responsabilita", "scelta"),
    ("La responsabilità più grande è rimanere se stessi", "responsabilita", "identita"),
    ("Ogni scelta lascia dietro di sé una vita non vissuta", "scelta", "rimpianto"),
    ("Scegliere è accettare di perdere qualcosa", "scelta", "coraggio"),
    ("Il dubbio è l'unico compagno che non mi ha mai mentito", "dubbio", "onesta"),
    ("Ho imparato a dubitare di chi non dubita mai", "dubbio", "verita"),
    ("Vorrei una sola certezza che duri più di una stagione", "certezza", "attesa"),
    ("Una certezza mi basta: domani ti chiamerò", "certezza", "promessa"),
    ("Il rimpianto è un amore che non ha trovato dove stare", "rimpianto", "amore"),
    ("Non rimpiango ciò che ho fatto, ma ciò che non ho detto", "rimpianto", "silenzio"),
    ("La colpa è un ospite che si siede a tavola con noi", "colpa", "famiglia"),
    ("Mi sono perdonato una colpa che nessuno ricordava", "colpa", "perdono"),
    ("Il pentimento arriva sempre un attimo dopo la porta chiusa", "pentimento", "porta"),
    ("Il pentimento sincero somiglia a una preghiera", "pentimento", "fede"),
    ("La distanza non uccide l'amore, lo mette alla prova", "distanza", "amore"),
    ("Mille chilometri e basta una voce per annullarli", "distanza", "connessione"),
    ("Certi incontri sembrano scritti prima di noi", "incontro", "destino"),
    ("Un incontro casuale ha cambiato la direzione di tutto", "incontro", "viaggio"),
    ("Mi basta uno sguardo per capire se sei sincero", "sguardo", "verita"),
    ("Mi hai guardato senza chiedermi niente, e mi sono sentito visto", "sguardo", "empatia"),
    ("Il tuo sorriso è la mia unità di misura del giorno", "sorriso", "felicita"),
    ("Sorrido anche quando non c'è niente da sorridere, per allenamento", "sorriso", "resilienza"),
    ("Le lacrime sono la lingua che il corpo parla quando le parole finiscono", "lacrime", "corpo"),
    ("Ho pianto di gioia per la prima volta e non sapevo come si faceva", "lacrime", "euforia"),
    ("Una risata condivisa ripara più di mille scuse", "risata", "perdono"),
    ("Ridevamo tanto che non ricordo di cosa", "risata", "amicizia"),
    ("Riconoscerei la tua voce tra mille anche dopo mille anni", "voce", "memoria"),
    ("Ho perso la voce per anni, poi ho cantato", "voce", "musica"),
    ("Le parole giuste arrivano sempre il giorno dopo", "parole", "pazienza"),
    ("A volte le parole sono muri travestiti da ponti", "parole", "ribellione"),
    ("Una piccola bugia mi ha protetto, e mi ha portato lontano da me", "bugia", "identita"),
    ("Dire la verità costa, mentire costa di più e a rate", "bugia", "onesta"),
    ("Le fiabe sono bugie che dicono il vero", "fiaba", "verita"),
    ("Mi leggevi una fiaba e il mondo si sistemava da solo", "fiaba", "infanzia"),
    ("L'eroe vero ha paura e va avanti lo stesso", "eroe", "paura"),
    ("Mio padre è stato il mio eroe finché ho scoperto che era umano", "eroe", "padre"),
    ("La guerra non finisce con la pace, finisce quando smettiamo di ricordarla", "guerra", "memoria"),
    ("Le guerre le combattono i giovani per il sogno dei vecchi", "guerra", "giovinezza"),
    ("Ogni confine è una cicatrice disegnata su una mappa", "confine", "cicatrice"),
    ("Ho attraversato un confine e ho lasciato metà del mio nome", "confine", "identita"),
    ("Essere stranieri è la forma più onesta di essere liberi", "straniero", "liberta"),
    ("Straniero ovunque, ma a casa dentro una canzone", "straniero", "musica"),
    ("Chi emigra porta una valigia di cartone e un mare dentro", "migrazione", "mare"),
    ("Migrare è chiedere al mondo un posto dove essere visti", "migrazione", "speranza"),
    ("La radio accesa di notte è una compagnia che non chiede nulla", "radio", "notte"),
    ("Alla radio ho sentito la nostra canzone e ho dovuto fermare la macchina", "radio", "musica"),
    ("Il telefono squilla e spero sia tu, ogni volta", "telefono", "speranza"),
    ("Non ti chiamo per orgoglio, e ogni sera lo rimpiango", "telefono", "orgoglio"),
    ("Ho riscritto quel messaggio venti volte e poi l'ho cancellato", "messaggio", "ansia"),
    ("Un messaggio inatteso ha aggiustato la mia giornata", "messaggio", "sorpresa"),
    ("Scrivere una lettera a mano è un gesto di resistenza", "lettera", "ribellione"),
    ("Ho ritrovato una tua lettera e ho pianto sulla prima riga", "lettera", "ricordo"),
    ("Una fotografia vecchia è un ricordo che ha smesso di muoversi", "fotografia", "nostalgia"),
    ("In quella foto non sapevamo ancora cosa sarebbe successo", "fotografia", "destino"),
    ("Un ricordo cambia ogni volta che lo racconto", "ricordo", "verita"),
    ("Il ricordo più bello è un odore, non un'immagine", "ricordo", "cibo"),
    ("L'oblio è una gentilezza che la mente concede al cuore", "oblio", "gentilezza"),
    ("Ho paura dell'oblio più che della morte", "oblio", "paura"),
    ("L'eternità dura quanto un bacio che non vuole finire", "eternita", "passione"),
    ("Cerco l'eternità nelle cose piccole, come il suono dell'acqua", "eternita", "semplicita"),
    ("La morte non è la fine, è un silenzio più grande", "morte", "silenzio"),
    ("Nessuno mi ha spiegato che la morte è anche per chi resta", "morte", "lutto"),
    ("Ogni nascita è una scommessa che il mondo vale la pena", "nascita", "speranza"),
    ("Quando sei nato ho smesso di avere paura del futuro", "nascita", "futuro"),
    ("La giovinezza è credere che il tempo sia infinito", "giovinezza", "tempo"),
    ("Da giovani si corre, da vecchi si cammina, e si vede di più", "giovinezza", "vecchiaia"),
    ("La maturità è smettere di dimostrare e cominciare a capire", "maturita", "consapevolezza"),
    ("Maturare è accettare che alcune domande non hanno risposta", "maturita", "mistero"),
    ("Un bambino ha chiesto perché il cielo è blu e io non ho saputo rispondere", "bambino", "curiosita"),
    ("Il bambino che ero mi guarda e chiede dove sono finiti i sogni", "bambino", "sogno"),
    ("Mia madre sa quando sto male prima di me", "madre", "empatia"),
    ("Le mani di mia madre sono la mia prima geografia", "madre", "mani"),
    ("Mio padre mi ha insegnato a stare in piedi senza insegnarmi a chiedere aiuto", "padre", "forza"),
    ("Papà dormiva sul divano con la radio accesa, e tutto era al sicuro", "padre", "sonno"),
    ("Mio fratello mi ha difeso e poi mi ha preso in giro per anni", "fratello", "complicita"),
    ("Con mio fratello condivido un linguaggio fatto di silenzi", "fratello", "silenzio"),
    ("I nonni sono il ponte tra il mondo che fu e quello che sarà", "nonni", "radici"),
    ("La voce di mia nonna al telefono è ancora la mia casa", "nonni", "casa"),
    ("Le mani raccontano la storia di una vita meglio degli occhi", "mani", "vecchiaia"),
    ("Una mano stretta nel momento giusto vale più di un discorso", "mani", "abbraccio"),
    ("Il cuore sa cose che la testa impiega anni a capire", "cuore", "consapevolezza"),
    ("Ho il cuore pieno e le tasche vuote, e va bene così", "cuore", "gratitudine"),
    ("Respirare piano è la prima forma di coraggio", "respiro", "coraggio"),
    ("Mi fermo e ascolto il respiro, e il mondo si rimette a posto", "respiro", "pace"),
    ("Ogni cicatrice è la prova che qualcosa ha provato a farmi male e ha perso", "cicatrice", "forza"),
    ("Le mie cicatrici sono mappe, non vergogne", "cicatrice", "vergogna"),
    ("Una ferita aperta insegna dove finisce il mio coraggio", "ferita", "paura"),
    ("Alcune ferite si chiudono solo quando smettiamo di toccarle", "ferita", "tempo"),
    ("Guarire non è dimenticare, è ricordare senza sanguinare", "guarigione", "memoria"),
    ("La guarigione arriva piano, di notte, mentre non guardi", "guarigione", "notte"),
    ("Prego senza sapere a chi, e va bene lo stesso", "preghiera", "fede"),
    ("La preghiera più sincera è un silenzio condiviso", "preghiera", "silenzio"),
    ("Un miracolo è vedere per la prima volta ciò che ho sempre guardato", "miracolo", "stupore"),
    ("Il vero miracolo è che ci siamo incontrati in miliardi di possibilità", "miracolo", "destino"),
    ("L'anima è quello che resta quando tolgo ogni ruolo", "anima", "identita"),
    ("Ho incontrato la tua anima prima del tuo nome", "anima", "connessione"),
    ("Dentro ho un vuoto che ha la forma esatta di qualcuno", "vuoto", "mancanza"),
    ("Il vuoto non va riempito, va ascoltato", "vuoto", "ascolto"),
    ("Passo la vita a cercare una cosa che ho già perso in infanzia", "ricerca", "infanzia"),
    ("Ogni risposta trovata mi ha regalato tre nuove domande", "ricerca", "curiosita"),
    ("Il futuro non mi spaventa quando c'è qualcuno accanto", "futuro", "fiducia"),
    ("Costruiamo il futuro un giorno alla volta, senza fretta", "futuro", "pazienza"),
    ("La mancanza è un modo di amare quando l'altro non c'è", "mancanza", "amore"),
    ("Mi manchi nei posti più stupidi, come in coda alla posta", "mancanza", "umorismo"),
]

FIXTURE_ENTRIES = [
    {"id": i, "text": text, "tags": list(tags)}
    for i, (text, *tags) in enumerate(_RAW, start=1)
]


def seed_test_data() -> None:
    db_local.init_db()
    rows = [
        {
            "id": e["id"],
            "text": e["text"],
            "created_at": None,
            "status": "test",
            "ip": None,
            "likes": 0,
        }
        for e in FIXTURE_ENTRIES
    ]
    db_local.upsert_entries(rows)
    for e in FIXTURE_ENTRIES:
        db_local.set_entry_tags(e["id"], e["tags"])
    log.info("Inserite %d entry di prova, gia' taggate", len(FIXTURE_ENTRIES))
